#!/usr/bin/env node

var fs = require('fs');
var path = require('path');
var csvWriter = require('csv-write-stream');

if (process.argv.length < 3) {
  process.stderr.write('Usage: write-name-index file1.json [file2.json file3.json ...] > output.csv');
  process.exit(1);
}

var inputFiles = process.argv.slice(2);

var writer = csvWriter({ headers: ['value', 'property', 'files'] });
writer.pipe(process.stdout);

var index = {};

inputFiles
.filter(function (file) { return /json$/.test(file); })
.forEach(function (file) {
  try {
    var proplist = JSON.parse(fs.readFileSync(file));
    proplist.forEach(function (props) {
      for (var key in props) {
        if (props[key] && props[key].length && /name/i.test(key)) {
          var k = encode(key, props[key]);
          index[k] = index[k] || [];
          index[k].push(path.basename(file.replace(/.properties.json/, '')));
        }
      }
    });
  } catch(e) {
    process.stderr.write('Error parsing properties for ' + file + '\n');
  }
});

for (var key in index) {
  var kv = decode(key);
  writer.write({
    value: kv[1],
    property: kv[0],
    files: index[key].join(';')
  });
}
writer.end();

function encode(key, value) {
  return JSON.stringify([key.toLowerCase(), value]);
}

function decode(encoded) {
  return JSON.parse(encoded);
}
